name: mobile
description: "Nobaro — An offline note engine."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.1
  audioplayers: ^6.8.1
  flutter_tts: ^4.2.5
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_mono.png

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Variable.ttf
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata-Variable.ttf
